name: Auto-Resolve Conflicts
on:
  pull_request:
    types: [synchronize, opened]

jobs:
  resolve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Resolve specific file conflicts automatically
        uses: VeyronSakai/conflict-resolver@v0.5.2
